### PR TITLE
Fix #2 - Retain path as NSString in workers

### LINKED ISSUE #2: Sporadic crash for 0.2.0
I have not been successful in creating repro steps. This only happens like every fifth time I run a script.

I'm using this module in an integration test, creating a file and tagging it with one tag.

The error I get is:

```
2014-08-11 22:06:37.801 node[36652:1034596] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'
*** First throw call stack:
(
    0   CoreFoundation                      0x00007fff8b044f3c __exceptionPreprocess + 172
    1   libobjc.A.dylib                     0x00007fff8d6a26de objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff8b044ded +[NSException raise:format:] + 205
    3   Foundation                          0x00007fff94b7f40d -[NSURL(NSURL) initFileURLWithPath:] + 131
    4   Foundation                          0x00007fff94b7f376 +[NSURL(NSURL) fileURLWithPath:] + 45
    5   osx_tag.node                        0x0000000100ff306a _ZN13AddTagsWorker7ExecuteEv + 66
    6   node                                0x0000000100150035 worker + 90
    7   node                                0x0000000100146335 uv__thread_start + 25
    8   libsystem_pthread.dylib             0x00007fff91756657 _pthread_body + 131
    9   libsystem_pthread.dylib             0x00007fff917565d4 _pthread_body + 0
    10  libsystem_pthread.dylib             0x00007fff91754821 thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    36652 abort      ./node_modules/cucumber/bin/cucumber.js
```

And I do not send in a null/nil value. Since the script works most of the times it does work and get all the required params.

Any ideas?

### PR DESCRIPTION
**Pull request by ZoneMR**
Fixes a race condition leading to null or invalid strings being used for NSURL creation.

### CODE REVIEW

**Comment by keichi** [comment]
Thanks @ZoneMR! Did this fix the crashing issue for you?

**Comment by ZoneMR** [comment]
Yes - tested extensively - used to get the crash a lot, now not at all.

**Comment by keichi** [comment]
Great, thanks for catching this.

**Comment by keichi** [comment]
FYI I just published a new release (0.4.4) including your fix.

**Comment by ZoneMR** [comment]
Thanks - much appreciated. I'm finding osx-tag very useful.

**Pull request merged**
