### PR TITLE
Update nan to version ~2.18.0

### PR DESCRIPTION
**Pull request by Cykelero**
The gyp build wouldn't work anymore in Node v21.1.0.

To do this update, I ran `npm install nan@latest`, then edited `package.json` to use a `~` specifier instead of the default `^`.

### CODE REVIEW

**Comment by keichi** [comment]
Hi @Cykelero, thanks for this! Could you take a look at the CI errors?

**Comment by Cykelero** [comment]
Sorry, I'm not super familiar with using node-gyp, so I'm not sure I understand what's going on exactly.

From the error message in the Node 16 and 18 runs (`ModuleNotFoundError: No module named 'distutils'`), my understanding is that the node-gyp in these versions relies on a Python package [that's been removed from recent Python versions](https://stackoverflow.com/questions/77233855/why-did-i-got-an-error-modulenotfounderror-no-module-named-distutils).

I don't know if explicitly adding this package to node-gyp's installation (as suggested by the StackOverflow answerer) is feasible.  
However, I assume newer versions of node have fixed their dependency on their deprecated package—I'm trying to check this by running the CI script with newer Node versions. (that's the `3b04a97` commit I just added; please approve the workflow change when you have time)

If the tests work, this means that the package will work for people who are up-to-date on their Node version.  
For users with older versions of Node, I assume the right move is for them to install a matching, older version of Python—maybe that's something that could be configured in the CI test workflow, if you don't want to outright remove these older versions from the test matrix?

**Comment by keichi** [comment]
It seems distutils was removed as of Python 3.12, and the current macOS-latest image on GitHub actions has only Python 3.12 installed. Fortunately node-gyp has been updated to remove the dependency on distutils (https://github.com/nodejs/node-gyp/issues/2869).

Can you try adding the latest `node-gyp` as a dev dependency (`npm i -D node-gyp`)?

**Comment by Cykelero** [comment]
Good catch! I assumed the bundled version of node-gyp would be up to date. Installing a newer version as you suggested does seem to work.
With one exception: node 14 tests seem to [fail with a different error](https://github.com/Cykelero/osx-tag/actions/runs/6971383407/job/18971333359?pr=1). I removed 14 from the CI list—is that OK?

(also, I accidentally closed this PR by pushing an empty branch. oops!)

**Comment by keichi** [comment]
Sure, since node 14 already reached EoL. I will bump the version requirement to >= 16 and publish a new release.
https://endoflife.date/nodejs

**Comment by Cykelero** [comment]
Brilliant, thank you!

**Pull request merged**
